(part "KPA-3010EC"
    (packageRef "APA3010ZGCGX")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "THERMAL_PAD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Manufacturer_Name" "Kingbright")
    (property "Manufacturer_Part_Number" "KPA-3010EC")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Kingbright/KPA-3010EC?qs=2JU0tDl2GZ2Xj2WABSYoCA%3D%3D")
    (property "Arrow_Part_Number" "KPA-3010EC")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/kpa-3010ec/kingbright?region=europe")
    (property "Description" "2.5 V Red LED Side View SMD, Kingbright KPA-3010EC")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/KPA-3010EC.pdf")
    (property "symbolName1" "KPA-3010EC")
)
