(part "NCV8730ASN330T1G"
    (packageRef "SOT95P275X110-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "NCV8730ASN330T1G")
    (property "Mouser_Part_Number" "863-NCV8730ASN330T1G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/NCV8730ASN330T1G?qs=GedFDFLaBXG9IOwczGXdzg%3D%3D")
    (property "Arrow_Part_Number" "NCV8730ASN330T1G")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ncv8730asn330t1g/on-semiconductor?region=nac")
    (property "Description" "LDO Regulator Pos 3.3V 0.15A Automotive 5-Pin TSOP T/R")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/2df29e4e0191e431728827d4926d2a47.pdf")
    (property "symbolName1" "NCV8730ASN330T1G")
)
