(part "MAX6070AAUT18+T"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "FILTER") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUTS") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "MAX6070AAUT18+T")
    (property "Mouser_Part_Number" "700-MAX6070AAUT18T")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Maxim-Integrated/MAX6070AAUT18%2bT?qs=fEkotVtiOiQPKIf6MZqOIA%3D%3D")
    (property "Arrow_Part_Number" "MAX6070AAUT18+T")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/max6070aaut18t/maxim-integrated?region=nac")
    (property "Description" "V-Ref Precision 1.8V 10mA 6-Pin SOT-23 T/R")
    (property "Datasheet_Link" "https://datasheets.maximintegrated.com/en/ds/MAX6070-MAX6071.pdf")
    (property "symbolName1" "MAX6070AAUT18+T")
)
